# Generated by Django 3.1.7 on 2021-03-16 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='d',
            field=models.CharField(max_length=100),
        ),
    ]
